server:
  port: 9000
spring:
  application:
    name: native-jpa
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        bytecode:
          provider: bytebuddy
        show_sql: true