name: Native Image

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-dev:
    name: 'Build Native Image ${{ matrix.platform }}'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: 'ubuntu-latest'
            platform: 'linux-amd64'
    runs-on: ${{matrix.os}}
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'liberica'
          java-version: '17'
          java-package: 'jdk'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: maven
      - name: Build
        shell: bash
        run: |
          mvn clean package && mvn -Pnative compile-no-fork
          ls target
          sleep 60
          mvn clean
